version: '3.4'
  
services:
#be carefull about 2spaces before first character !!!!!!!!!!!  

  catalogdb:
    image: mongo
  
  basketdb: 
    image: redis:alpine

  portainer:
    image: portainer/portainer-ce

  discountdb: 
    image: postgres 

  pgadmin:
    image: dpage/pgadmin4


  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.Api/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.Api/Dockerfile

volumes:
  mongo_data:
  portainer_data:
  postgres_data:
  pgadmin_data:

